spring.application.name=backend

spring.datasource.url=jdbc:sqlite:${SQLITE_DB_PATH:database.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
# spring.sql.init.mode=always

# MyBatisの設定
mybatis.mapper-locations=classpath:mapper/*.xml

# JWTの設定
jwt.secret-key=${JWT_SECRET}

google.maps.api-key=${GOOGLE_MAPS_API_KEY}